# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrMHCOVH4AYoqWevBEhLu522jO1Kz3XP
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

data=pd.read_excel('/content/Sexual Harassment Data for Machine Learning Project.xlsx')
data.shape

data.head()

data=data.drop(['Area','Zone'],axis=1)
data.head()

x=data.drop(['Class'],axis=1)
y=data['Class']
print(x.shape)
print(y.shape)

data.replace({'Time':{'Morning':0,'Afternoon':1,'Evening':2,'Night':3}},inplace=True)
data.replace({'People.Frequency':{'Low':0,'Medium':1,'High':2}},inplace=True)
data.replace({'Is.Police_Station':{'No':0,'Yes':1}},inplace=True)
data.replace({'Is.Bar':{'No':0,'Yes':1}},inplace=True)
data.replace({'Tier':{'Inner':0,'Middle':1,'Outer':2}},inplace=True)
data.replace({'Residence.Level':{'Low':0,'Medium':1,'High':2}},inplace=True)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.1, random_state=42, stratify=y)

x.head()

model=LogisticRegression()
model.fit(x_train,y_train)
predict=model.predict(x_train)

from sklearn import metrics
error=metrics.accuracy_score(y_train,predict)

print(error)

predict=model.predict(x_test)
error=metrics.accuracy_score(y_test,predict)
print(error)